version: "3"
services:
  gatewayservice:
    image: registry.digitalocean.com/cfe-k8s-rsoi/gatewayservice
    build:
      context: ./Gatewayservice
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app/Gatewayservice
  paymentservice:
    image: registry.digitalocean.com/cfe-k8s-rsoi/paymentservice
    build:
      context: ./PaymentService
    restart: always
    ports:
      - "8060:8060"
    volumes:
      - .:/app/PaymentService
  loyaltyservice:
    image: registry.digitalocean.com/cfe-k8s-rsoi/loyaltyservice
    build:
      context: ./LoyaltyService
    restart: always
    ports:
      - "8050:8050"
    volumes:
      - .:/app/LoyaltyService
  reservationservice:
    image: registry.digitalocean.com/cfe-k8s-rsoi/reservationservice
    build:
      context: ./ReservationService
    restart: always
    ports:
      - "8070:8070"
    volumes:
      - .:/app/ReservationService
