# Generated by Django 4.1.2 on 2022-11-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_uid',
            new_name='hotelUid',
        ),
    ]
