# Generated by Django 4.1.2 on 2022-11-04 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_rename_hotel_uid_hotel_hoteluid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
