# Generated by Django 4.1.2 on 2022-11-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0003_alter_reservation_payment_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='payment_uid',
            new_name='paymentUid',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_uid',
            new_name='reservationUid',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_date',
            new_name='startDate',
        ),
    ]
