# Generated by Django 4.1.2 on 2022-11-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('reservation_count', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=10)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
