# Generated by Django 4.1.2 on 2022-11-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loyalty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userloyalty',
            old_name='reservation_count',
            new_name='reservationCount',
        ),
    ]
