# Generated by Django 4.1.2 on 2022-11-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loyalty', '0002_rename_reservation_count_userloyalty_reservationcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloyalty',
            name='status',
            field=models.CharField(default='BRONZE', max_length=10),
        ),
    ]
