# Generated by Django 4.1.2 on 2022-11-04 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
