# Generated by Django 4.1.2 on 2022-11-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_alter_payment_payment_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_uid',
            new_name='paymentUid',
        ),
    ]
